---
- name: Install PostgreSQL Server
  yum: name={{ item }} state=present
  with_items:
    - postgresql-server
    - postgresql-devel
- name: Install psycopg2 for PostgreSQL functions in Ansible
  yum: name=python-psycopg2 state=present
- name: Initialise database
  command: postgresql-setup initdb creates=/var/lib/pgsql/data/pg_hba.conf
- name: Install pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/data/pg_hba.conf
  register: pg_hba_install
  become: yes
- name: Enable PostgreSQL service
  service: name=postgresql enabled=yes
- name: Start PostgreSQL service
  service: name=postgresql state=restarted
  when: pg_hba_install.changed
- name: Create users
  postgresql_user: name={{ item['username'] }} password={{ item['password'] }} role_attr_flags={{ item['role_attr_flags'] }}
  with_items: '{{ pg_users }}'
  become: true
  become_user: postgres
- name: Create databases
  postgresql_db: name={{ item['database'] }} owner="{{ item['owner'] }}" state=present
  with_items: '{{ pg_databases }}'
  become: true
  become_user: postgres
- name: Update privileges of databases
  postgresql_privs: db={{ item['database'] }} type=database privs={{ item['privileges'] }} roles={{ item['username'] }} state=present
  with_items: '{{ pg_privileges }}'
  become: true
  become_user: postgres
- name: Update privileges of database objects
  postgresql_privs: db={{ item['database'] }} type={{ item['type'] }} privs={{ item['privileges'] }} roles={{ item['username'] }} objs={{ item['objs'] }} state=present
  with_items: '{{ pg_privileges_objs }}'
  become: true
  become_user: postgres
