---
- name: Install nginx
  yum: name=nginx state=present
- name: Configure nginx
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
- name: Configure site
  template: src=site.conf.j2 dest=/etc/nginx/conf.d/{{ item['file_name'] }}.conf
  with_items: '{{ nginx_sites }}'
- name: Start nginx service
  service: name=nginx state=restarted enabled=yes
- include: selinux-policy.yml
