---
- name: Install libselinux-python
  yum: name=libselinux-python state=present
- name: Install libsemanage-python
  yum: name=libsemanage-python state=present
- name: Install policycoreutils-python-utils
  yum: name=policycoreutils-python state=present
