---
- hosts: all
  roles:
    - role: selinux
      become: yes
    - role: build-essential
      become: yes
    - role: git-install
      become: yes
  tasks:
    - name: Create symlink of gpg2 as gpg
      file: src=/usr/bin/gpg2 dest=/usr/bin/gpg state=link
      become: yes
    - name: Create deploy group
      group: name=deploy state=present
      become: yes
    - name: Create deploy user
      user: name=deploy shell=/bin/bash groups=deploy password={{ hostvars['default']['unix.passwords.deploy'] }} state=present
      become: yes
    - name: Create directory for server applications
      file: path=/var/server owner=deploy group=deploy state=directory
      become: yes
