---
- hosts: all
  roles:
    - role: selinux
      become: yes
  tasks:
    - group: name=deploy state=present
      become: yes
    - user: name=deploy shell=/bin/bash groups=deploy password={{ hostvars['default']['unix.passwords.deploy'] }} state=present
      become: yes
