---
- hosts: all
  roles:
    - role: selinux
      become: yes
    - role: build-essential
      become: yes
    - role: git-install
      become: yes
  tasks:
    - name: Create symlink of gpg2 as gpg
      file: src=/usr/bin/gpg2 dest=/usr/bin/gpg state=link
      become: yes
    - name: Create deploy group
      group: name=deploy state=present
      become: yes
    - name: Create deploy user
      user: name=deploy shell=/bin/bash groups=deploy password={{ hostvars[inventory_hostname]['unix.passwords.deploy'] |password_hash('sha512') }} state=present
      become: yes
    - name: Create directory for server applications
      file: path=/var/server owner=deploy group=deploy state=directory
      become: yes
    - name: Install yum-utils
      yum: name=yum-utils state=present
      become: yes
    - name: Install EPEL (epel-release)
      yum: name=epel-release state=present
      become: yes
    - name: Install centos-release-scl
      yum: name=centos-release-scl state=present
      become: yes
    - name: Enable RHSCL repository
      shell: yum-config-manager --enable rhel-server-rhscl-7-rpms
      become: yes
    - name: SSH port configuration
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'Port [1-9]+'
        line: Port {{ hostvars[inventory_hostname]['sshd.port'] }}
      become: yes
    - name: Check SSH port configuration in SELinux
      shell: semanage port --list | grep -E "ssh_port_t\\s+tcp.*\\s+{{ hostvars[inventory_hostname]['sshd.port'] }}[,$]" -q
      register: ssh_selinux_port_set
      changed_when: False
      failed_when: False
      become: yes
    - name: Set SSH port configuration in SELinux
      shell: semanage port --add -t ssh_port_t -p tcp {{ hostvars[inventory_hostname]['sshd.port'] }}
      when: ssh_selinux_port_set.rc != 0
      become: yes
