---
- hosts: all
  roles:
    - role: php-pgsql
      become: yes
    - role: davical
      deploy_user: deploy
      postgres_user: postgres
      instances:
        - domain_name: braden-walters.info
          sysabbr: davical
          system_name: DAViCal CalDAV Server
          admin_email: 'public@braden-walters.info'
          postgres:
            dbname: davical
            dbuser: davical_app
            dbpass: "{{ hostvars[inventory_hostname]['postgresql.passwords.davical_app'] }}"
