---
- hosts: all
  roles:
    - role: postgresql
      become: yes
      pg_users:
        - username: deploy
          password: "{{ hostvars[inventory_hostname]['postgresql.passwords.deploy'] }}"
          role_attr_flags: SUPERUSER
        - username: application
          password: "{{ hostvars[inventory_hostname]['postgresql.passwords.application'] }}"
          role_attr_flags: LOGIN
      pg_databases:
        - database: kksystem
          owner: application
      pg_privileges:
        - database: kksystem
          objs: ALL_IN_SCHEMA
          username: deploy,application
          privileges: ALL
