---
- hosts: all
  roles:
    - role: postgresql
      become: yes
      pg_users:
        - username: deploy
          password: "{{ hostvars['default']['postgresql.passwords.deploy'] }}"
          role_attr_flags: SUPERUSER
        - username: application
          password: "{{ hostvars['default']['postgresql.passwords.application'] }}"
          role_attr_flags: LOGIN
