---
- include: base.yml
- include: www.yml
- include: letsencrypt.yml
- include: database.yml
- include: mail.yml
- include: haskell.yml
- include: ruby.yml
- include: personal-site.yml
- include: kksystem.yml
- include: caldav.yml
