---
- hosts: all
  roles:
    - role: nginx
      become: yes
      nginx_sites:
        - file_name: 'default'
          port: 80
          root_path: '/var/www/default'
        - file_name: 'meosite'
          server_name: 'braden-walters.info www.braden-walters.info'
          port: 80
          root_path: '/var/www/meosite'
        - file_name: 'kksystem'
          server_name: 'kksystem.org www.kksystem.org'
          port: 80
          redirect_https: yes
        - file_name: 'kksystem-ssl'
          server_name: 'kksystem.org www.kksystem.org'
          port: '443 ssl'
          proxy_pass: 'http://unix:/var/server/kksystem/passenger.sock:/'
          additional_params:
            ssl_certificate: /etc/letsencrypt/live/www.kksystem.org/fullchain.pem
            ssl_certificate_key: /etc/letsencrypt/live/www.kksystem.org/privkey.pem
            include: /etc/letsencrypt/nginx.conf
        - file_name: 'davical'
          server_name: 'braden-walters.info www.braden-walters.info'
          port: 8443
          root_path: '/usr/local/share/davical/htdocs'
          index: index.php
          has_php: yes
    - role: php
      become: yes
    - role: php-fpm-pools
      become: yes
      php_fpm_pools:
        - file_name: 'davical'
          host_name: 'braden-walters.info'
          php_values:
            include_path: '/usr/local/share/awl/inc'
  tasks:
    - name: Create /var/www directory
      file: path=/var/www state=directory owner=deploy group=deploy recurse=yes setype=httpd_sys_content_t
      become: yes
