---
- name: Fetch over Git
  git: repo=https://github.com/meoblast001/meosite.git dest=/var/server/meosite
  become: yes
  become_user: "{{ deploy_user }}"
- name: Create Cabal sandbox
  command: cabal sandbox init
  args:
    chdir: /var/server/meosite
    creates: /var/server/meosite/.cabal-sandbox
  become: yes
  become_user: "{{ deploy_user }}"
- name: Install Configuration.hs
  copy: src=Configuration.hs dest=/var/server/meosite/Configuration.hs
  become: yes
  become_user: "{{ deploy_user }}"
- name: Install dependencies and build project over Cabal
  shell: cabal update && cabal install --only-dependencies && cabal build
  args:
    chdir: /var/server/meosite
    creates: /var/server/meosite/dist/build/site/site
  become: yes
  become_user: "{{ deploy_user }}"
- name: Create web directory /var/www/meosite
  file: path=/var/www/meosite state=directory owner=deploy
  become: yes
- name: Install code-graph in crontab
  cron: name=code-graph state=present
  args:
    value: /var/server/meosite/dist/build/code-graph/code-graph meoblast001 /var/www/meosite /home/deploy/error.code-graph.log
    user: deploy
    minute: 0
    hour: 6
  become: yes
