---
- name: Fetch over Git
  git: repo=https://github.com/meoblast001/kksystem.git dest=/var/server/kksystem force=yes
- name: Remove references to unused gems from Gemfile
  lineinfile: line="gem '{{ item }}'" dest=/var/server/kksystem/Gemfile state=absent
  with_items:
    - "sqlite3"
    - "mysql"
- name: Add passenger to Gemfile
  lineinfile: line="gem 'passenger'" dest=/var/server/kksystem/Gemfile state=present
- name: Bundle install
  bundler: state=present executable=~/.gem/bin/bundle chdir=/var/server/kksystem
- name: Install user_config.rb
  template: src=user_settings.rb.j2 dest=/var/server/kksystem/config/user_settings.rb
- name: Install database.yml
  template: src=database.yml.j2 dest=/var/server/kksystem/config/database.yml
- name: Install simple_form
  shell: RAILS_ENV=production bin/rails generate simple_form:install
  args:
    creates: /var/server/kksystem/config/initializers/simple_form.rb
    chdir: /var/server/kksystem
