---
- name: Add repository peterson/ghc-8.0.1
  shell: yum-config-manager --add-repo=https://copr.fedorainfracloud.org/coprs/petersen/ghc-8.0.1/repo/epel-7/petersen-ghc-8.0.1-epel-7.repo --enable
- name: Install ghc and cabal-install
  yum: name={{ item }} state=present
  with_items:
    - "ghc"
    - "cabal-install"
