---
- name: Check if chruby exists
  stat: path=/usr/local/bin/chruby-exec
  register: chruby_exec_file
- name: Install chruby
  include: chruby_install.yml
  when: chruby_exec_file.stat.exists == False
- name: Check if ruby-install exists
  stat: path=/usr/local/bin/ruby-install
  register: ruby_install_file
- name: Install ruby-install
  include: ruby_install_install.yml
  when: ruby_install_file.stat.exists == False
- name: Install rubies
  command: "/usr/local/bin/ruby-install {{ item }} creates=/home/{{ ruby_user }}/.rubies/{{ item }}"
  become: yes
  become_user: "{{ ruby_user }}"
  with_items: "{{ ruby_versions }}"
