---
- name: "Create directory /var/run/{{ service_name }}"
  file: path=/var/run/{{ service_name }} state=directory owner={{ deploy_user }} group={{ deploy_user }}
  become: yes
- name: Install control script
  template: src=railsctl.sh.j2 dest={{ ctl_script }} mode=755
  become: yes
- name: Install systemd service file
  template: src=service.j2 dest=/usr/lib/systemd/system/{{ service_name }}.service
  become: yes
- name: Reexecute systemd daemon manager (apparent SELinux problem)
  shell: systemctl daemon-reexec
  become: yes
  changed_when: False
- name: Enable and start systemd service
  systemd: name={{ service_name }} state=started enabled=yes
  become: yes
