---
- name: Install passenger
  shell: "source ~/.bashrc && gem install passenger"
  args:
    creates: /home/deploy/.gem/bin/passenger
  become: yes
  become_user: "{{ deploy_user }}"
- include: selinux-policy.yml
