---
- name: Query list of SELinux modules
  shell: semodule -l
  register: selinuxmodules
  become: yes
  check_mode: no
  changed_when: False
- name: Copy passenger_systemd.te to system
  copy: src=passenger_systemd.te dest=/tmp/passenger_systemd.te
  become: yes
  when: "selinuxmodules.stdout.find('passenger_systemd') == -1"
- name: Generate passenger_systemd.mod
  shell: checkmodule -M -m -o passenger_systemd.mod passenger_systemd.te
  args:
    chdir: /tmp
  become: yes
  when: "selinuxmodules.stdout.find('passenger_systemd') == -1"
- name: Generate passenger.pp
  shell: semodule_package -o passenger_systemd.pp -m passenger_systemd.mod
  args:
    chdir: /tmp
  become: yes
  when: "selinuxmodules.stdout.find('passenger_systemd') == -1"
- name: Install passenger with semodule
  shell: semodule -i /tmp/passenger_systemd.pp
  become: yes
  when: "selinuxmodules.stdout.find('passenger_systemd') == -1"
- name: Reload policy
  shell: semodule --reload
  become: yes
  when: "selinuxmodules.stdout.find('passenger_systemd') == -1"
