---
- name: Install php, php-cli, and php-fpm
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-cli
    - php-fpm
- name: Enable and start php-fpm
  service: name=php-fpm enabled=yes state=started
